version: 2
updates:
#  - package-ecosystem: gradle
#    directory: "/"
#    schedule:
#      interval: "weekly"
#      time: "04:00"
#      timezone: Europe/Berlin
#    open-pull-requests-limit: 20
#  - package-ecosystem: github-actions
#    directory: "/"
#    schedule:
#      interval: "weekly"
